package br.gov.go.agr.siav.models;

import jedi.db.models.CharField;
import jedi.db.models.Manager;
import jedi.db.models.Model;
import jedi.db.models.QuerySet;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.experimental.Accessors;

@Data
@EqualsAndHashCode(callSuper = false)
@Accessors(fluent = false, chain = true)
@NoArgsConstructor
@AllArgsConstructor
public class Empresa extends Model {

    private static final long serialVersionUID = 1L;

    @CharField(max_length = 255, required = false)
    private String registroAgr;

    @CharField(max_length = 18, required = false)
    private String cnpj;

    @CharField(max_length = 255, required = false)
    private String razaoSocial;

    @CharField(max_length = 255, required = false)
    private String nomeFantasia;

    @CharField(max_length = 255, required = false)
    private String endereco;

    @CharField(max_length = 30, required = false)
    private String telefone;
    
    @CharField(max_length = 100, required = false)
    private String email;

    @CharField(max_length = 255, required = false)
    private String contato;


    public static Manager objects = new Manager(Empresa.class);

    // Generated by Jedi ORM
    public QuerySet<AutorizacaoViagem> getAutorizacaoViagemSet() {
        return AutorizacaoViagem.objects.getSet(Empresa.class, this.id);
    }

}
