package br.gov.go.agr.siav.models;

import jedi.db.models.CharField;
import jedi.db.models.Manager;
import jedi.db.models.Model;
import jedi.db.models.QuerySet;
import jedi.db.models.Table;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.experimental.Accessors;

@Data
@EqualsAndHashCode(callSuper = false)
@Accessors(fluent = false, chain = true)
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "fabricantes_veiculo")
public class FabricanteVeiculo extends Model {

    private static final long serialVersionUID = -786284931684821562L;

    @CharField(max_length = 255, unique = true)
    private String nome;

    public static Manager objects = new Manager(FabricanteVeiculo.class);

    // Generated by Jedi ORM
    public QuerySet<ModeloVeiculo> getModeloVeiculoSet() {
        return ModeloVeiculo.objects.getSet(FabricanteVeiculo.class, this.id);
    }

}
