package br.gov.go.agr.siav.models;

import jedi.db.models.CharField;
import jedi.db.models.ForeignKeyField;
import jedi.db.models.Manager;
import jedi.db.models.Model;
import jedi.db.models.QuerySet;
import jedi.db.models.Table;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.experimental.Accessors;

@Data
@EqualsAndHashCode(callSuper = false)
@Accessors(fluent = false, chain = true)
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "modelos_veiculo")
public class ModeloVeiculo extends Model {

    private static final long serialVersionUID = -2132781112762474260L;

    @CharField(max_length = 255, unique = true)
    private String nome;

    @ForeignKeyField
    private FabricanteVeiculo fabricante;

    public static Manager objects = new Manager(ModeloVeiculo.class);

    // Generated by Jedi ORM
    public QuerySet<Veiculo> getVeiculoSet() {
        return Veiculo.objects.getSet(ModeloVeiculo.class, this.id);
    }

}
