package br.gov.go.agr.siav.models;

import java.math.BigDecimal;

import jedi.db.models.CharField;
import jedi.db.models.DateTimeField;
import jedi.db.models.DecimalField;
import jedi.db.models.IntegerField;
import jedi.db.models.Manager;
import jedi.db.models.Model;
import jedi.db.models.Table;
import jedi.types.DateTime;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.experimental.Accessors;

@Data
@EqualsAndHashCode(callSuper = false)
@Accessors(fluent = false, chain = true)
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "notas_fiscais")
public class NotaFiscal extends Model {

    private static final long serialVersionUID = -5471415470334729890L;

    @DecimalField
    private BigDecimal valor;

    @CharField(max_length = 10)
    private String serie;

    @IntegerField(unique = true)
    private Integer numero;

    @DateTimeField(auto_now_add = true, auto_now = true)
    private DateTime dataEmissao;

    public static Manager objects = new Manager(NotaFiscal.class);

    // Generated by Jedi ORM
    public AutorizacaoViagem getAutorizacaoViagem() {
        return AutorizacaoViagem.objects.get("nota_fiscal_id", this.id);
    }

}
