package br.gov.go.agr.siav.models;

import jedi.db.models.CharField;
import jedi.db.models.Manager;
import jedi.db.models.ManyToManyField;
import jedi.db.models.Model;
import jedi.db.models.QuerySet;
import jedi.db.models.Table;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.experimental.Accessors;

@Data
@EqualsAndHashCode(callSuper = false)
@Accessors(fluent = false, chain = true)
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "perfis")
public class Perfil extends Model {

    private static final long serialVersionUID = 2248704666728587601L;

    @CharField(max_length = 255, unique = true)
    private String nome;

    @CharField(max_length = 255, required = false)
    private String descricao;

    @CharField(max_length = 7, default_value = "Ativo")
    private String situacao;

    @ManyToManyField(through = Privilegio.class)
    private QuerySet<Permissao> permissoes = new QuerySet<>();

    public static Manager objects = new Manager(Perfil.class);

    // Generated by Jedi ORM
    public QuerySet<Usuario> getUsuarioSet() {
        return Usuario.objects.getSet(Perfil.class, this.id);
    }

    // Generated by Jedi ORM
    public QuerySet<Permissao> getPermissoes() {
        permissoes = new QuerySet<Permissao>();
        Permissao permissao = null;
        for (Privilegio privilegio : getPrivilegioSet()) {
            permissao = Permissao.objects.<Permissao>get("id", privilegio.getPermissao().getId());
            permissoes.add(permissao);
        }
        return permissoes;
    }

    // Generated by Jedi ORM
    public QuerySet<Privilegio> getPrivilegioSet() {
        return Privilegio.objects.getSet(Perfil.class, this.id);
    }
}
