package br.gov.go.agr.siav.models;

import jedi.db.models.CharField;
import jedi.db.models.Manager;
import jedi.db.models.Model;
import jedi.db.models.QuerySet;
import jedi.db.models.Table;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.experimental.Accessors;

@Data
@EqualsAndHashCode(callSuper = false)
@Accessors(fluent = false, chain = true)
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "permissoes")
public class Permissao extends Model {

    private static final long serialVersionUID = 5219228705658283982L;

    @CharField(max_length = 255, unique = false)
    private String nome;

    @CharField(max_length = 255, required = false, default_value = "")
    private String descricao;

    @CharField(max_length = 7, default_value = "Ativo")
    private String situacao;

    public static Manager objects = new Manager(Permissao.class);

    // Generated by Jedi ORM
    public QuerySet<Perfil> getPerfilSet() {
        QuerySet<Perfil> perfilList = new QuerySet<Perfil>();
        Perfil perfil = null;
        for (Privilegio privilegio : getPrivilegioSet()) {
            perfil = Perfil.objects.<Perfil>get("id", privilegio.getPerfil().getId());
            perfil.getPermissoes();
            perfilList.add(perfil);
        }
        return perfilList;
    }

    // Generated by Jedi ORM
    public QuerySet<Privilegio> getPrivilegioSet() {
        return Privilegio.objects.getSet(Permissao.class, this.id);
    }
}
