package br.gov.go.agr.siav.models;

import jedi.db.models.CharField;
import jedi.db.models.FloatField;
import jedi.db.models.Manager;
import jedi.db.models.Model;
import jedi.db.models.QuerySet;
import jedi.db.models.Table;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.experimental.Accessors;

@Data
@EqualsAndHashCode(callSuper = false)
@Accessors(fluent = false, chain = true)
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "roteiros_viagem")
public class RoteiroViagem extends Model {

    private static final long serialVersionUID = -8226505200291010691L;

    @CharField(max_length = 255)
    private String origem;

    @CharField(max_length = 255)
    private String destino;

    @FloatField
    private Float distancia;

    public static Manager objects = new Manager(RoteiroViagem.class);

    // Generated by Jedi ORM
    public QuerySet<AutorizacaoViagem> getAutorizacaoViagemSet() {
        return AutorizacaoViagem.objects.getSet(RoteiroViagem.class, this.id);
    }

}
