package br.gov.go.agr.siav.models;

import jedi.db.models.CharField;
import jedi.db.models.ForeignKeyField;
import jedi.db.models.IntegerField;
import jedi.db.models.Manager;
import jedi.db.models.Model;
import jedi.db.models.QuerySet;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.experimental.Accessors;

@Data
@EqualsAndHashCode(callSuper = false)
@Accessors(fluent = false, chain = true)
@NoArgsConstructor
@AllArgsConstructor
public class Veiculo extends Model {

    private static final long serialVersionUID = 272867263616594328L;

    @CharField(max_length = 255)
    private String placa;

    @CharField(max_length = 255)
    private String numero;

    @CharField(max_length = 255)
    private String tipo;

    @CharField(max_length = 4)
    private String anoFabricacao;

    @IntegerField
    private int lotacao;

    @CharField(max_length = 255)
    private String primeiroMotorista;

    @CharField(max_length = 255)
    private String cnhPrimeiroMotorista;

    @CharField(max_length = 255, required = false)
    private String segundoMotorista;

    @CharField(max_length = 255, required = false)
    private String cnhSegundoMotorista;

    @ForeignKeyField
    private ModeloVeiculo modelo;

    public static Manager objects = new Manager(Veiculo.class);

    // Generated by Jedi ORM
    public QuerySet<AutorizacaoViagem> getAutorizacaoViagemSet() {
        return AutorizacaoViagem.objects.getSet(Veiculo.class, this.id);
    }
}
