package br.gov.go.agr.siav.models;

import jedi.db.models.CharField;
import jedi.db.models.DateTimeField;
import jedi.db.models.FloatField;
import jedi.db.models.IntegerField;
import jedi.db.models.Manager;
import jedi.db.models.Model;
import jedi.db.models.Table;
import jedi.types.DateTime;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.experimental.Accessors;

@Data
@EqualsAndHashCode(callSuper = false)
@Accessors(fluent = false, chain = true)
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "viagens")
public class Viagem extends Model {

    private static final long serialVersionUID = 8926689880440634193L;

    @IntegerField
    private Integer quantidadePassageiros;

    @DateTimeField(auto_now_add = true, auto_now = true)
    private DateTime dataSaida;

    @DateTimeField(auto_now_add = true, auto_now = true)
    private DateTime dataRetorno;

    @FloatField
    private Float extensao;

    @CharField(max_length = 255, default_value = "NÃO INFORMADO")
    private String localSaida;

    @CharField(max_length = 11)
    private String tipo;

    public static Manager objects = new Manager(Viagem.class);

    // Generated by Jedi ORM
    public AutorizacaoViagem getAutorizacaoViagem() {
        return AutorizacaoViagem.objects.get("viagem_id", this.id);
    }
}
